import type { Metadata } from "next";
import { Geist, Lato, Geist_Mono } from "next/font/google";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Configure the Lato font
const lato = Lato({
  weight: ['300','400', '700'], // Specify weights you need
  subsets: ['latin'],
  variable: '--font-lato', // CSS variable name
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
